//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBDrivingSchoolEntities : DbContext
    {
        public DBDrivingSchoolEntities()
            : base("name=DBDrivingSchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<district> district { get; set; }
        public virtual DbSet<package> package { get; set; }
        public virtual DbSet<type> type { get; set; }
        public virtual DbSet<user_package> user_package { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
